"""questions/answers

Revision ID: 077dc019035a
Revises: 8c378ef9e10b
Create Date: 2024-03-04 23:17:15.062444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '077dc019035a'
down_revision: Union[str, None] = '8c378ef9e10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    # ### end Alembic commands ###
