"""vocab learning3

Revision ID: 1096e348569a
Revises: 12056637126a
Create Date: 2024-02-21 22:11:22.113871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1096e348569a'
down_revision: Union[str, None] = '12056637126a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VocabsCategorys', 'order',
               existing_type=mysql.ENUM('middle_school', 'high_school', 'college', 'toefl', 'gre', 'grad'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VocabsCategorys', 'order',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('middle_school', 'high_school', 'college', 'toefl', 'gre', 'grad'),
               existing_nullable=True)
    # ### end Alembic commands ###
