"""submission revision

Revision ID: 12fbcfc50d8a
Revises: 59ca4cd7acf7
Create Date: 2024-01-30 13:52:17.821178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12fbcfc50d8a'
down_revision: Union[str, None] = '59ca4cd7acf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Submissions', 'stem_weight',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('Submissions', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Submissions', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('Submissions', 'stem_weight',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
