"""fks

Revision ID: 1e5845a9c581
Revises: e42c53cea404
Create Date: 2024-01-17 19:39:06.956135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e5845a9c581'
down_revision: Union[str, None] = 'e42c53cea404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Accounts_ibfk_4', 'Accounts', type_='foreignkey')
    op.drop_constraint('TaskAccounts_ibfk_1', 'TaskAccounts', type_='foreignkey')
    op.add_column('Users', sa.Column('vocab_level', sa.String(length=6), nullable=True))
    op.drop_column('Users', 'vacab_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('vacab_level', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('Users', 'vocab_level')
    op.create_foreign_key('TaskAccounts_ibfk_1', 'TaskAccounts', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Accounts_ibfk_4', 'Accounts', 'Exams', ['exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
