"""new tables add

Revision ID: 1f95b257b0cc
Revises: 85bdc99d0085
Create Date: 2024-02-07 17:43:13.667290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f95b257b0cc'
down_revision: Union[str, None] = '85bdc99d0085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['Patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_sheet_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['AnswerSheetRecord.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['Sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ScoresRubric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('rubric', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['Sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ScoresRubric')
    op.drop_table('Scores')
    op.drop_table('Menu')
    # ### end Alembic commands ###
