"""questions/answers

Revision ID: 2199516eb783
Revises: cc9ceb1850d7
Create Date: 2024-03-03 12:37:50.738973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2199516eb783'
down_revision: Union[str, None] = 'cc9ceb1850d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('voice_content', sa.Text(), nullable=True))
    op.alter_column('Questions', 'voice_link',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('Submissions', 'voice_link',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('Submissions', 'video_link',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('Submissions', 'upload_file_link',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Submissions', 'upload_file_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Submissions', 'video_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Submissions', 'voice_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Questions', 'voice_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('Questions', 'voice_content')
    # ### end Alembic commands ###
