"""accounts

Revision ID: 2414b183a903
Revises: da91eae92443
Create Date: 2024-03-07 21:16:44.562729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2414b183a903'
down_revision: Union[str, None] = 'da91eae92443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
