"""questions/answers

Revision ID: 2b8b11925be0
Revises: 2199516eb783
Create Date: 2024-03-04 23:12:08.556813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b8b11925be0'
down_revision: Union[str, None] = '2199516eb783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LearningTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Submissions', sa.Column('model_answer', sa.Text(), nullable=True))
    op.add_column('TaskAccounts', sa.Column('learning_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TaskAccounts', 'LearningTypes', ['learning_type'], ['id'], ondelete='CASCADE')
    op.add_column('VocabsLearningRecords', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', 'Accounts', ['accounts_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'account_id')
    op.drop_constraint(None, 'TaskAccounts', type_='foreignkey')
    op.drop_column('TaskAccounts', 'learning_type')
    op.drop_column('Submissions', 'model_answer')
    op.drop_table('LearningTypes')
    # ### end Alembic commands ###
