"""account unique

Revision ID: 2e984dea0d2e
Revises: dcd884a0898c
Create Date: 2024-01-17 15:03:05.522088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e984dea0d2e'
down_revision: Union[str, None] = 'dcd884a0898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='Accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'Accounts', ['user_id'], unique=True)
    # ### end Alembic commands ###
