"""add tables

Revision ID: 2f51d2a97ae6
Revises: 8b0c8b3f6ebf
Create Date: 2024-03-22 15:58:55.805984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f51d2a97ae6'
down_revision: Union[str, None] = '8b0c8b3f6ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StudyPulseRecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('time_length', sa.Float(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Accounts', sa.Column('current_status', sa.Enum('middle_school', 'high_school', 'college', 'prof', name='status'), nullable=True))
    op.add_column('Accounts', sa.Column('purpose', sa.Enum('study_board', 'work_demand', 'personal_improve', name='purpose'), nullable=True))
    op.add_column('Accounts', sa.Column('study_type', sa.Enum('studying', 'prepare_studying', 'self_studying', name='study'), nullable=True))
    op.add_column('Accounts', sa.Column('next_test_time', sa.DateTime(), nullable=True))
    op.add_column('AnswerSheetRecord', sa.Column('father_sheet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AnswerSheetRecord', 'father_sheet')
    op.drop_column('Accounts', 'next_test_time')
    op.drop_column('Accounts', 'study_type')
    op.drop_column('Accounts', 'purpose')
    op.drop_column('Accounts', 'current_status')
    op.drop_table('StudyPulseRecords')
    # ### end Alembic commands ###
