"""account fk

Revision ID: 3407cfbdb3fa
Revises: c3cd1a3a556a
Create Date: 2024-01-17 19:03:08.056523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3407cfbdb3fa'
down_revision: Union[str, None] = 'c3cd1a3a556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Accounts', 'exam_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint('Accounts_ibfk_2', 'Accounts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Accounts_ibfk_2', 'Accounts', 'Exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('Accounts', 'exam_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
