"""account_words

Revision ID: 3802099803fb
Revises: f9873884b103
Create Date: 2024-03-26 09:52:37.788843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3802099803fb'
down_revision: Union[str, None] = 'f9873884b103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountConfigs',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('config_link', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.drop_table('account_vocab')
    op.drop_table('account_scores')
    op.add_column('Accounts', sa.Column('account_vocab_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Accounts', 'account_vocab_level')
    op.create_table('account_scores',
    sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_link', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account_vocab',
    sa.Column('account_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_link', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('AccountConfigs')
    # ### end Alembic commands ###
