"""word constrains

Revision ID: 3c68406fb55e
Revises: 1096e348569a
Create Date: 2024-02-23 09:11:13.877466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c68406fb55e'
down_revision: Union[str, None] = '1096e348569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Vocabs', ['word'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vocabs', type_='unique')
    # ### end Alembic commands ###
