"""task_flow

Revision ID: 466702016d05
Revises: 4274011e2ca1
Create Date: 2024-02-23 22:29:06.854415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '466702016d05'
down_revision: Union[str, None] = '4274011e2ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TaskFlowsConditions', 'in_function',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('TaskFlowsConditions', 'out_function',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TaskFlowsConditions', 'out_function',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('TaskFlowsConditions', 'in_function',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
