"""similarities

Revision ID: 4c3e080eaa65
Revises: e33fde6829df
Create Date: 2024-02-23 20:27:45.794448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c3e080eaa65'
down_revision: Union[str, None] = 'e33fde6829df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VocabCategorySimilarities', 'word_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VocabCategorySimilarities', 'word_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
