"""word constrains

Revision ID: 577cc16b0201
Revises: f3849832e7d9
Create Date: 2024-02-23 09:22:45.937443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '577cc16b0201'
down_revision: Union[str, None] = 'f3849832e7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vocabs', 'word',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'Vocabs', ['word'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vocabs', type_='unique')
    op.alter_column('Vocabs', 'word',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
