"""text size revision

Revision ID: 59ca4cd7acf7
Revises: c715777ae3eb
Create Date: 2024-01-29 17:19:07.386375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ca4cd7acf7'
down_revision: Union[str, None] = 'c715777ae3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('has_ans', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Questions', 'has_ans')
    # ### end Alembic commands ###
