"""last change

Revision ID: 65b787ae4e45
Revises: f87ca18a423a
Create Date: 2024-03-31 22:11:37.839245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65b787ae4e45'
down_revision: Union[str, None] = 'f87ca18a423a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Accounts', sa.Column('est_score', sa.Float(), nullable=True))
    op.alter_column('Indicators', 'indicator_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('Indicators', 'father_indicator',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('TaskAccounts', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('TaskAccounts', sa.Column('due_time', sa.DateTime(), nullable=True))
    op.add_column('TaskAccounts', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('plan_due_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'plan_due_time')
    op.drop_column('TaskAccounts', 'level')
    op.drop_column('TaskAccounts', 'due_time')
    op.drop_column('TaskAccounts', 'status')
    op.alter_column('Indicators', 'father_indicator',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Indicators', 'indicator_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=40),
               existing_nullable=False)
    op.drop_column('Accounts', 'est_score')
    # ### end Alembic commands ###
