"""add time

Revision ID: 6f75371a30ef
Revises: 70c16b81f983
Create Date: 2024-02-08 20:42:12.675372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f75371a30ef'
down_revision: Union[str, None] = '70c16b81f983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Scores', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('Scores', sa.Column('last_update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Scores', 'last_update_time')
    op.drop_column('Scores', 'create_time')
    # ### end Alembic commands ###
