"""total score

Revision ID: 70c16b81f983
Revises: 1f95b257b0cc
Create Date: 2024-02-07 17:53:37.442671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c16b81f983'
down_revision: Union[str, None] = '1f95b257b0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Scores', sa.Column('total_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Scores', 'total_score')
    # ### end Alembic commands ###
