"""size revision

Revision ID: 83a2dceaa03d
Revises: b26d3eb1cf5d
Create Date: 2024-01-29 12:00:20.335195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83a2dceaa03d'
down_revision: Union[str, None] = 'b26d3eb1cf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Questions', 'question_stem',
               existing_type=mysql.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('Questions', 'stem_weights',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('Questions', 'correct_answer',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('Questions', 'keywords',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Resources', 'resource_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('Resources', 'resource_eng_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.add_column('Submissions', sa.Column('submit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Submissions', 'submit_time')
    op.alter_column('Resources', 'resource_eng_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('Resources', 'resource_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('Questions', 'keywords',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Questions', 'correct_answer',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Questions', 'stem_weights',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('Questions', 'question_stem',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###
