"""question_type

Revision ID: 88737f97c299
Revises: c50b1e8a6809
Create Date: 2024-03-09 03:21:16.166874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88737f97c299'
down_revision: Union[str, None] = 'c50b1e8a6809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Questions', 'remark',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Questions', 'remark',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
