"""questions/answers

Revision ID: 8c378ef9e10b
Revises: 2b8b11925be0
Create Date: 2024-03-04 23:14:37.553224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c378ef9e10b'
down_revision: Union[str, None] = '2b8b11925be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TaskAccounts', 'learning_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('VocabsLearningRecords', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', 'Accounts', ['accounts_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'account_id')
    op.alter_column('TaskAccounts', 'learning_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
