"""accounts

Revision ID: 92814fb2ceed
Revises: 2414b183a903
Create Date: 2024-03-07 21:18:58.809770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92814fb2ceed'
down_revision: Union[str, None] = '2414b183a903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('VocabsLearningRecords', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.alter_column('VocabsLearningRecords', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
