"""questions/answers

Revision ID: 985af64a39df
Revises: 077dc019035a
Create Date: 2024-03-04 23:41:41.851309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '985af64a39df'
down_revision: Union[str, None] = '077dc019035a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.drop_column('Tasks', 'order')
    # ### end Alembic commands ###
