"""Accounts f_k

Revision ID: 9bd2c3dcb5a1
Revises: 577cc16b0201
Create Date: 2024-02-23 20:15:00.869009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd2c3dcb5a1'
down_revision: Union[str, None] = '577cc16b0201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearning', sa.Column('today_learn', sa.String(length=20), nullable=False))
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['accounts_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    op.drop_column('VocabsLearning', 'today_learn')
    # ### end Alembic commands ###
