"""vocab learning2

Revision ID: a18f044d7858
Revises: db09ed4378b5
Create Date: 2024-02-21 21:45:50.236947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a18f044d7858'
down_revision: Union[str, None] = 'db09ed4378b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TaskFlows', 'condition_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'TaskFlows', 'TaskFlowsConditions', ['condition_id'], ['id'], ondelete='CASCADE')
    op.drop_column('TaskFlows', 'account_id')
    op.add_column('Vocabs', sa.Column('word_c', sa.Text(), nullable=False))
    op.alter_column('Vocabs', 'word',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=False)
    op.drop_column('Vocabs', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vocabs', sa.Column('level', mysql.ENUM('middle_school', 'high_school', 'college', 'toefl', 'gre', 'grad'), nullable=True))
    op.alter_column('Vocabs', 'word',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('Vocabs', 'word_c')
    op.add_column('TaskFlows', sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'TaskFlows', type_='foreignkey')
    op.alter_column('TaskFlows', 'condition_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
