"""questions/answers

Revision ID: a3c29bfc0bb2
Revises: 985af64a39df
Create Date: 2024-03-04 23:43:16.835649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3c29bfc0bb2'
down_revision: Union[str, None] = '985af64a39df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['accounts_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    # ### end Alembic commands ###
