"""question_type

Revision ID: c50b1e8a6809
Revises: 92814fb2ceed
Create Date: 2024-03-09 00:00:09.924109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c50b1e8a6809'
down_revision: Union[str, None] = '92814fb2ceed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Questions', 'question_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Questions', 'question_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
