"""accounts

Revision ID: da91eae92443
Revises: a3c29bfc0bb2
Create Date: 2024-03-07 21:14:03.118497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da91eae92443'
down_revision: Union[str, None] = 'a3c29bfc0bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_plan', sa.Integer(), nullable=True))
    op.add_column('VocabsLearningRecords', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key(None, 'VocabsLearningRecords', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'accounts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VocabsLearningRecords', sa.Column('accounts_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'VocabsLearningRecords', type_='foreignkey')
    op.create_foreign_key('VocabsLearningRecords_ibfk_5', 'VocabsLearningRecords', 'Accounts', ['accounts_id'], ['id'], ondelete='CASCADE')
    op.drop_column('VocabsLearningRecords', 'account_id')
    op.drop_column('Users', 'user_plan')
    # ### end Alembic commands ###
