"""vocab learning

Revision ID: db09ed4378b5
Revises: 6f75371a30ef
Create Date: 2024-02-21 21:36:33.926735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db09ed4378b5'
down_revision: Union[str, None] = '6f75371a30ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskFlowsConditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('in_function', sa.String(length=30), nullable=False),
    sa.Column('out_function', sa.String(length=30), nullable=False),
    sa.Column('current_module_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_module_id'], ['Modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VocabsCategorys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Enum('middle_school', 'high_school', 'college', 'toefl', 'gre', 'grad', name='level'), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VocabsLearningRecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewed_word_id', sa.Integer(), nullable=True),
    sa.Column('study_word_id', sa.Integer(), nullable=True),
    sa.Column('wrong_word_id', sa.Integer(), nullable=True),
    sa.Column('correct_word_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correct_word_id'], ['Vocabs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_word_id'], ['Vocabs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_word_id'], ['Vocabs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wrong_word_id'], ['Vocabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VocabCategoryRelationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['VocabsCategorys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['Vocabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VocabsLearning',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('in_process', sa.String(length=20), nullable=False),
    sa.Column('finished', sa.String(length=20), nullable=False),
    sa.Column('to_review', sa.String(length=20), nullable=False),
    sa.Column('unknown', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('current_category', sa.Integer(), nullable=True),
    sa.Column('last_day_review', sa.Integer(), nullable=True),
    sa.Column('last_day_study', sa.Integer(), nullable=True),
    sa.Column('today_day_study', sa.Integer(), nullable=True),
    sa.Column('today_day_review', sa.Integer(), nullable=True),
    sa.Column('total_study', sa.Integer(), nullable=True),
    sa.Column('total_review', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_category'], ['VocabsCategorys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'Accounts', 'Exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.add_column('TaskAccounts', sa.Column('loop', sa.Integer(), nullable=True))
    op.add_column('TaskAccounts', sa.Column('current_loop', sa.Integer(), nullable=True))
    op.add_column('TaskFlows', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('TaskFlows', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TaskFlows', 'TaskFlowsConditions', ['condition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'TaskFlows', 'Accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.add_column('Vocabs', sa.Column('word_c', sa.Text(), nullable=False))
    op.alter_column('Vocabs', 'word',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=False)
    op.drop_column('Vocabs', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vocabs', sa.Column('level', mysql.ENUM('middle_school', 'high_school', 'college', 'toefl', 'gre', 'grad'), nullable=True))
    op.alter_column('Vocabs', 'word',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('Vocabs', 'word_c')
    op.drop_constraint(None, 'TaskFlows', type_='foreignkey')
    op.drop_constraint(None, 'TaskFlows', type_='foreignkey')
    op.drop_column('TaskFlows', 'condition_id')
    op.drop_column('TaskFlows', 'account_id')
    op.drop_column('TaskAccounts', 'current_loop')
    op.drop_column('TaskAccounts', 'loop')
    op.drop_constraint(None, 'Accounts', type_='foreignkey')
    op.drop_table('VocabsLearning')
    op.drop_table('VocabCategoryRelationships')
    op.drop_table('VocabsLearningRecords')
    op.drop_table('VocabsCategorys')
    op.drop_table('TaskFlowsConditions')
    # ### end Alembic commands ###
