"""account unique

Revision ID: dcd884a0898c
Revises: 
Create Date: 2024-01-17 15:02:48.955734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd884a0898c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Accounts_ibfk_1', 'Accounts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Accounts_ibfk_1', 'Accounts', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
