"""account exam

Revision ID: e42c53cea404
Revises: 3407cfbdb3fa
Create Date: 2024-01-17 19:03:57.846295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e42c53cea404'
down_revision: Union[str, None] = '3407cfbdb3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Accounts', 'exam_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Accounts', 'Exams', ['exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Accounts', type_='foreignkey')
    op.alter_column('Accounts', 'exam_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
