"""account fk

Revision ID: f029ab4430ad
Revises: 2e984dea0d2e
Create Date: 2024-01-17 15:03:23.886712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f029ab4430ad'
down_revision: Union[str, None] = '2e984dea0d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Accounts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Accounts', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Accounts', type_='foreignkey')
    op.alter_column('Accounts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
