"""indicators

Revision ID: f72cc02b0f49
Revises: 7e76051559e2
Create Date: 2024-03-20 20:35:13.251555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72cc02b0f49'
down_revision: Union[str, None] = '7e76051559e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Indicators', sa.Column('indicator_descriptions', sa.Text(), nullable=True))
    op.add_column('Indicators', sa.Column('identifier', sa.Text(), nullable=True))
    op.add_column('Indicators', sa.Column('solve_steps', sa.Text(), nullable=True))
    op.add_column('Indicators', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Indicators', 'skills')
    op.drop_column('Indicators', 'solve_steps')
    op.drop_column('Indicators', 'identifier')
    op.drop_column('Indicators', 'indicator_descriptions')
    # ### end Alembic commands ###
