"""dele特、

Revision ID: f7de5e7cf93d
Revises: f029ab4430ad
Create Date: 2024-01-17 15:48:22.499803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7de5e7cf93d'
down_revision: Union[str, None] = 'f029ab4430ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Modules_ibfk_1', 'Modules', type_='foreignkey')
    op.drop_column('Modules', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Modules', sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Modules_ibfk_1', 'Modules', 'Tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
