"""Interger

Revision ID: f87ca18a423a
Revises: 3802099803fb
Create Date: 2024-03-29 10:09:03.997352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f87ca18a423a'
down_revision: Union[str, None] = '3802099803fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'vocab_level',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'vocab_level',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
