# 打卡
DAILY_STUDY_TIME_TARGET = 60 * 30  # 单位为秒 （20分钟）
DAILY_STUDY_LOGIN_COUNT_TARGET = 3  # 3次登陆

# 访问模型次数
NON_MEMBER_MODEL_AMOUNT = 1
NON_MEMBER_VOCAB_GREEN_TIME = 1 * 24 * 60 * 60  # 单位为秒 (一天）
MEMBER_DAY_OFF = 49

# Vocab
JUMP_NEED_STUDY_AMOUNT = 35  # 要学满35个
JUMP_NEED_PERCENTAGE = 90  # 90%
WORDS_STUDY = 5
STUDY_LOOP = 2

# 做题
LAST_X_RECORD = 7
WORST_X_TAGS = 5

