# Generated by Django 3.2.19 on 2023-12-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
