# Generated by Django 3.2.19 on 2024-01-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20231225_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='microserviceregister',
            name='method',
            field=models.CharField(help_text='请求方法', max_length=5, null='GET', verbose_name='请求方法'),
            preserve_default='GET',
        ),
    ]
