# Generated by Django 3.2.19 on 2024-01-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_microserviceregister_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=40, null=True, verbose_name='姓名'),
        ),
    ]
