# Generated by Django 3.2.19 on 2024-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='user_use',
            field=models.BooleanField(default=False, help_text='是否为前台用户所用', verbose_name='是否为前台用户所用'),
        ),
    ]
